before_script:
  - echo "Before script"
  - cd /var/www/devtestnet2/data/www/kfp.devtestnet.com/ #your project path


building:
  stage: build
#  when: manual
  only:
    - develop
  script:
    - PHP_VER=74
    - NODE_VER=14
    - PHP=/opt/php${PHP_VER}/bin/php
    - git reset --hard
    - git pull origin develop
    - ${PHP} artisan down || true
    - nvm use ${NODE_VER}
    - ${PHP} composer.phar install
    - npm install
    - npm run dev
    - ${PHP} artisan migrate:reset
    - ${PHP} artisan migrate
    - ${PHP} artisan db:seed
    - ${PHP} artisan optimize
    - ${PHP} artisan route:cache
    - ${PHP} artisan config:cache
    - ${PHP} artisan view:cache
    - ${PHP} artisan up

