before_script:
  - echo "Before script"
  - cd /var/www/devtestnet2/data/www/ #your project path

building:
  stage: build
  when: manual
  only: develop
  script:
    - echo "IT WORKS" > gitlab-ci.txt
